### ISSUE TITLE
Giá trị đối tượng bị thay đổi không rõ nguyên do

### ISSUE THREAD

**Issue by KafkaWannaFly** [tarzanchemgio/BigIntergerProject#1]
Dù luôn cẩn thận sử dụng `const` nhưng đôi khi giá trị của biến vẫn có thể bị thay đổi không rõ lý do.
![singularity](https://user-images.githubusercontent.com/47100782/69477584-7ef2c780-0e1a-11ea-849f-921126a914b9.jpg)
Ở trường hợp trên, chương trình hẳn sẽ báo lỗi vì không thể chia cho 0 nhưng...
![console](https://user-images.githubusercontent.com/47100782/69477590-9762e200-0e1a-11ea-8847-3067d391ad0d.jpg)
Vì lý do nào đó, biến `neg` đã mang giá trị là `1`
Khảo sát cho thấy, có vẻ như `neg` đã thay đổi giá trị sau khi làm phép trừ (dòng 21). Tuy nhiên, bản thân `operator-` không hề có lỗi. 

Hãy thử 1 ví dụ khác. Chỉ cần thay đổi nhẹ thứ tự các dòng code.
![singularity2](https://user-images.githubusercontent.com/47100782/69477663-7949b180-0e1b-11ea-8dee-39d3d373a17d.jpg)
Và BÙM!
![console2](https://user-images.githubusercontent.com/47100782/69477687-b6ae3f00-0e1b-11ea-9528-00dec9ed6856.jpg)

**GIẢI QUYẾT**
Tôi dự đoán rằng lỗi này xuất hiện do code "nén ép" kiểu  `(pos - neg).getDecimal()`. Cho nên, để an toàn thì hãy chịu khó làm từng bước như sau và hy vọng sẽ debug ra lỗi nếu còn gặp lại.
![solution](https://user-images.githubusercontent.com/47100782/69477729-6d122400-0e1c-11ea-80f0-9c3afe84d088.jpg)

**Comment by daoleviethoang** [comment]
Sent from Mail for Windows 10 From: Kafka Wanna FlySent: 29 Tháng Mười Một 2019 8:02 SATo: tarzanchemgio/BigIntergerProjectCc: SubscribedSubject: Re: [tarzanchemgio/BigIntergerProject] Giá trị đối tượng bị thay đổi không rõ nguyên do (#1) Closed #1.Perfect—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.
